services:
  palu-express-dev:
    container_name: palu-express-dev
    build:
      context: .
      dockerfile: Dockerfile.express
      target: development
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

  palu-express-prod:
    container_name: palu-express-prod
    build:
      context: .
      dockerfile: Dockerfile.express
      target: production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
